import Navigation, { Brand } from "@/components/navigation";
import { ArrowRight, Check, Heart, Lock, Sparkle } from "@/components/icons";

const steps = [
  ["01", "Tell your story", "Speak or type in the language that feels most natural to you."],
  ["02", "Shape it with Bridge", "Our guided tools help you find clear, authentic English."],
  ["03", "Open new doors", "Use your story confidently in applications and interviews."],
];

export default function Home() {
  return <main id="top" className="overflow-hidden">
    <div className="bg-sky"><Navigation />
      <section className="relative mx-auto max-w-6xl px-5 pb-20 pt-12 lg:px-8 lg:pb-28 lg:pt-20">
        <div className="dot-grid absolute -right-8 top-0 h-64 w-64 opacity-50" />
        <div className="relative grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]">
          <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#C9E3F6] bg-white/70 px-3.5 py-2 text-xs font-semibold text-[#367CAC]"><Heart className="h-4 w-4" />Made for learners rebuilding their future</div>
            <h1 className="serif max-w-xl text-5xl leading-[1.05] tracking-tight text-ink sm:text-6xl">Your story can <span className="text-[#2D80B6]">open doors.</span></h1>
            <p className="mt-6 max-w-lg text-lg leading-relaxed text-[#52708B]">Bridge helps crisis-affected learners turn their experiences into clear, powerful English — for the opportunities ahead.</p>
            <div className="mt-8 flex flex-wrap gap-3"><a href="/tell-your-story" className="inline-flex items-center gap-2 rounded-full bg-[#1F6D9F] px-6 py-3.5 font-semibold text-white shadow-sm transition hover:bg-[#175982]">Start your story <ArrowRight className="h-4 w-4" /></a><a href="#how-it-works" className="rounded-full border border-[#B8D9EF] bg-white px-6 py-3.5 font-semibold text-[#286B9B] transition hover:border-[#7CB6DA]">See how it works</a></div>
            <p className="mt-5 flex items-center gap-2 text-sm text-[#64819A]"><Lock className="h-4 w-4" />Private, respectful, and always in your control.</p>
          </div>
          <StoryCard />
        </div>
      </section>
    </div>
    <section className="bg-white py-10"><div className="mx-auto flex max-w-5xl flex-wrap items-center justify-center gap-x-12 gap-y-5 px-5 text-center text-sm font-medium text-[#7792A8]"><span>Built with learners</span><span className="h-1 w-1 rounded-full bg-[#A3C5DD]"/><span>Guided by educators</span><span className="h-1 w-1 rounded-full bg-[#A3C5DD]"/><span>Trusted by community partners</span></div></section>
    <section id="how-it-works" className="mx-auto max-w-6xl px-5 py-20 lg:px-8 lg:py-28"><div className="max-w-xl"><p className="text-sm font-bold uppercase tracking-[.16em] text-[#4385B2]">A gentler way forward</p><h2 className="serif mt-3 text-4xl leading-tight text-ink">Your words matter. We help them travel further.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{steps.map(([number, title, copy]) => <article key={number} className="rounded-3xl bg-white p-7 shadow-soft"><span className="text-sm font-bold text-[#73ADD2]">{number}</span><h3 className="mt-10 text-xl font-bold text-ink">{title}</h3><p className="mt-3 leading-relaxed text-[#627F97]">{copy}</p><div className="mt-7 h-1 w-10 rounded-full bg-[#BDE1F5]" /></article>)}</div></section>
    <section id="start" className="bg-[#DDF1FF] py-20"><div className="mx-auto max-w-6xl px-5 lg:px-8"><div className="grid overflow-hidden rounded-[2rem] bg-[#1C5D8A] shadow-soft lg:grid-cols-2"><div className="p-9 text-white sm:p-12"><Sparkle className="h-7 w-7 text-[#A9DAFA]"/><h2 className="serif mt-7 text-4xl leading-tight">A place to begin, without pressure.</h2><p className="mt-5 max-w-md leading-relaxed text-[#D4E9F7]">You do not need perfect English. Bring the story you have, and we’ll take one small step at a time.</p><a href="#signin" className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 font-semibold text-[#1C5D8A]">Create your free account <ArrowRight className="h-4 w-4" /></a></div><div className="flex items-end justify-center bg-[#EAF7FF] px-8 pt-12"><div className="w-full max-w-sm rounded-t-[2rem] bg-white p-6 shadow-soft"><p className="text-xs font-bold uppercase tracking-wider text-[#6D9DBB]">Your next chapter</p><p className="serif mt-3 text-2xl text-ink">“I want to study nursing so I can care for my community.”</p><div className="mt-6 flex items-center gap-2 text-sm font-semibold text-[#2D78AF]"><Check className="h-5 w-5" />Story saved safely</div></div></div></div></div></section>
    <section id="for-partners" className="mx-auto max-w-6xl px-5 py-20 text-center lg:px-8"><p className="text-sm font-bold uppercase tracking-[.16em] text-[#4385B2]">For organizations</p><h2 className="serif mx-auto mt-3 max-w-2xl text-4xl leading-tight text-ink">Help more learners find the words for what comes next.</h2><p className="mx-auto mt-5 max-w-xl leading-relaxed text-[#627F97]">Bridge works alongside schools, NGOs, and community programs to make opportunity more accessible.</p><a className="mt-7 inline-block font-semibold text-[#216A9B] underline decoration-[#90C5E5] underline-offset-4" href="#contact">Partner with Bridge →</a></section>
    <footer id="about-us" className="border-t border-[#DCEBF5] bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-8 px-5 py-10 lg:flex-row lg:items-center lg:justify-between lg:px-8"><Brand /><p className="text-sm text-[#7792A8]">Stories that open doors.</p><div id="signin" className="flex gap-5 text-sm font-medium text-[#52708B]"><a href="#privacy">Privacy</a><a id="contact" href="mailto:hello@bridge.example">Contact</a></div></div></footer>
  </main>;
}

function StoryCard() { return <div className="relative mx-auto w-full max-w-md"><div className="absolute -left-9 top-12 h-36 w-36 rounded-full bg-[#C7E9FA]"/><div className="relative rounded-[2rem] bg-white p-5 shadow-soft sm:p-7"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#D9F1FF] font-bold text-[#2474A7]">M</div><div><p className="text-sm font-bold text-ink">My story</p><p className="text-xs text-[#7792A8]">Draft · Just now</p></div></div><span className="rounded-full bg-[#E3F5E9] px-3 py-1 text-xs font-bold text-[#387B55]">Saved</span></div><div className="mt-6 rounded-2xl bg-[#F3F9FD] p-5"><p className="text-sm leading-relaxed text-[#466A86]">“When I arrived in a new city, I felt unsure. But every day I learned something new, and I started helping other families...”</p></div><div className="mt-5 flex items-center gap-3 rounded-2xl border border-[#D7EBF8] p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#E2F3FF] text-[#2D80B6]"><Sparkle className="h-5 w-5" /></span><p className="text-sm font-medium text-[#3F6682]">Bridge is helping you express this clearly.</p></div></div></div>; }
